server:
  port: 8080
spring:
  redis:
    host: 192.168.0.111
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: 5
        max-idle: 10
        min-idle: 0
    timeout: 1000
spring.data.queryDataUrl: http://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/MoneyFlow.ssl_bkzj_ssggzj


